version: '3.7'

services:
  blogs:
    build:
      dockerfile: Dockerfile
      context: ./
    image: encounters-web-server
    container_name: encounters-container
    restart: always
    networks:
      - servers
    ports:
      - "4000:4000"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
    networks:
      - servers
    environment:
      MONGO_INITDB_DATABASE: SOAencounters
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb-data:
    name: mongodb-data

networks:
  servers:
    name: servers
    driver: bridge